receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

exporters:
    signalfx:
      access_token: ${SPLUNK_ACCESS_TOKEN}  #  "7UJVg1u8H_VidUkksxyJKQ"
      access_token_passthrough: true
      realm: us1
      timeout: 5s
      max_idle_conns: 80
      #api_url: https://api.us1.signalfx.com #  https://api.${REALM}.signalfx.com
      #correlation: null
      #ingest_url: https://ingest.us1.signalfx.com #  https://ingest.${REALM}.signalfx.com
      #sync_host_metadata: true
    debug:
      verbosity: detailed
processors:
    batch:

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    telemetry:
      logs:
        level: debug
    extensions: [pprof, zpages, health_check]
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug,signalfx]
